[package]
name = "voxel-tiler-core"
version = "0.1.0"
authors = ["azishio"]
edition = "2021"
description = "Convert point clouds to voxel data."

documentation = "https://docs.rs/voxel-tiler-core"
homepage = "https://crates.io/crates/voxel-tiler-core"
repository = "https://github.com/azishio/voxel-tiler-core-rs"

readme = "README.md"

keywords = ["voxel", "point-cloud", "las", "ply"]
categories = ["concurrency", "data-structures", "encoding", "mathematics", "science::geo"]
license = "MIT OR Apache-2.0"

exclude = ["examples", "benches"]

[dependencies]
coordinate-transformer = "1.5.0"
fxhash = "0.2.1"
indexmap = "2.2.6"
las = { version = "0.8.7", optional = true }
laz = { version = "0.9.1", optional = true }
num = "0.4.3"
ordered-float = "4.2.0"
ply-rs = "0.1.3"
rayon = { version = "1.10.0", optional = true }
vec-x = "0.7.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = []
rayon = ["dep:rayon", "laz/parallel", "las/laz-parallel"]
jamalloc = ["dep:tikv-jemallocator"]
print-warning = []

[[example]]
name = "write_voxel_tiles"
path = "examples/write_voxel_tiles.rs"
required-features = ["print-warning"]

[[example]]
name = "write_voxel"
path = "examples/write_voxel.rs"
required-features = ["print-warning"]

[[example]]
name = "read_ply"
path = "examples/read_ply.rs"
required-features = ["las", "print-warning"]


[[bench]]
name = "create_voxel"
path = "benches/create_voxel.rs"
harness = false
required-features = ["las"]

[[bench]]
name = "par_create_voxel"
path = "benches/par_create_voxel.rs"
harness = false
required-features = ["rayon", "las"]
