[package]
name = "voxel-tiler"
version = "0.1.0"
edition = "2021"

[dependencies]
coordinate-transformer = "1.4.0"
fxhash = "0.2.1"
indexmap = "2.2.6"
num = "0.4.3"
ordered-float = "4.2.0"
ply-rs = "0.1.3"
vec-x = "0.1.1"
