[package]
name = "voxel-tiler"
version = "0.1.0"
edition = "2021"

[dependencies]
coordinate-transformer = "1.5.0"
fxhash = "0.2.1"
indexmap = "2.2.6"
las = { version = "0.8.7", optional = true }
laz = { version = "0.9.1", optional = true }
num = "0.4.3"
ordered-float = "4.2.0"
ply-rs = "0.1.3"
rayon = { version = "1.10.0", optional = true }
vec-x = "0.7.0"

[[example]]
name = "create_voxel_tile_ply"
path = "examples/write_voxel_tiles.rs"
required-features = ["las"]

[[example]]
name = "create_voxel_ply"
path = "examples/write_voxel.rs"
required-features = ["las"]

[[example]]
name = "read_ply"
path = "examples/read_ply.rs"

[features]
default = ["rayon", "print-warning"]
rayon = ["dep:rayon", "laz/parallel", "las/laz-parallel"]
print-warning = []
